### ISSUE TITLE
How to implement own posterframe?

### ISSUE THREAD

**Issue by toccamonium-fe** [nelsonglory/ng_fastyoutube#2]
Hi, thanks for extension. But I'm missing the field where I can select the posterframe image?

**Comment by nelsonglory** [comment]
Hi,

you can't choose between different poster images because there is only  
one to fetch which is generated by youtube in different resolutions.  
But it should be possible either to choose the generated poster  
picture for your own uploaded videos in youtube or in the uploaded  
video itself.

Zitat von toccamonium-fe ***@***.***>:

> Hi, thanks for extension. But I'm missing the field where I can  
> select the posterframe image?
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/nelsonglory/ng_fastyoutube/issues/2
> You are receiving this because you are subscribed to this thread.
>
> Message ID: ***@***.***>



-- 
ZIK
Pädagogische Hochschule Freiburg
Kunzenweg 21
79104 Freiburg, Germany

Tel: (+49) 761 682 359
Fax: (+49) 761 682 486
--
